[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.19.1",
    "clerk-backend-api>=7.0.0",
    "cloudinary>=1.46.0",
    "fastapi[standard]>=0.141.1",
    "psycopg>=3.3.4",
    "psycopg2-binary>=2.9.12",
    "pydantic-settings>=2.15.0",
    "python-dotenv>=1.2.3",
    "sqlalchemy>=2.0.52",
    "uvicorn[standard]>=0.52.4",
]
